=== CreativeCodingLab/corpusbrowser/corpora/MICASE-CD/micasex.dtd
<!-- edited with XMLSPY v5 rel. 4 U (http://www.xmlspy.com) by Gemma Lum (University of Michigan) -->
<!-- MICASE DTD, based loosely on the TEI, with a local extension for OVERLAP. -->
<!-- xmlified by LB -->
<!ELEMENT TEI.2 (TEIHEADER, TEXT)>
<!ATTLIST TEI.2
	N CDATA #IMPLIED
	ID CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "TEI.2"
>
<!ELEMENT TEICORPUS.2 (TEIHEADER, TEI.2+)>
<!ATTLIST TEICORPUS.2
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "TEICORPUS.2"
>
<!ELEMENT TEIHEADER (FILEDESC, PROFILEDESC)>
<!ATTLIST TEIHEADER
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TYPE CDATA "TEXT"
	CREATOR CDATA #IMPLIED
	STATUS (NEW | UPDATE) "NEW"
	DATE.CREATED CDATA #IMPLIED
	DATE.UPDATED CDATA #IMPLIED
	TEIFORM CDATA "TEIHEADER"
>
<!ELEMENT FILEDESC (TITLESTMT, PUBLICATIONSTMT, SOURCEDESC+)>
<!ATTLIST FILEDESC
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "FILEDESC"
>
<!ELEMENT TITLESTMT (TITLE+, (RESPSTMT)*)>
<!ATTLIST TITLESTMT
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "TITLESTMT"
>
<!ELEMENT RESPSTMT (RESP | NAME)*>
<!ATTLIST RESPSTMT
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "RESPSTMT"
>
<!ELEMENT RESP (#PCDATA)>
<!ATTLIST RESP
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "RESP"
>
<!ELEMENT PUBLICATIONSTMT (P+ | (PUBLISHER | DISTRIBUTOR | AUTHORITY | PUBPLACE | ADDRESS | IDNO | AVAILABILITY | DATE)+)>
<!ATTLIST PUBLICATIONSTMT
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "PUBLICATIONSTMT"
>
<!ELEMENT PUBLISHER (#PCDATA)>
<!ATTLIST PUBLISHER
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "PUBLISHER"
>
<!ELEMENT PUBPLACE (#PCDATA)>
<!ATTLIST PUBPLACE
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "PUBPLACE"
>
<!ELEMENT DISTRIBUTOR (#PCDATA)>
<!ATTLIST DISTRIBUTOR
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "DISTRIBUTOR"
>
<!ELEMENT AUTHORITY (#PCDATA)>
<!ATTLIST AUTHORITY
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "AUTHORITY"
>
<!ELEMENT IDNO (#PCDATA)>
<!ATTLIST IDNO
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TYPE CDATA #IMPLIED
	TEIFORM CDATA "IDNO"
>
<!ELEMENT AVAILABILITY (P)+>
<!ATTLIST AVAILABILITY
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	STATUS (FREE | UNKNOWN | RESTRICTED) #IMPLIED
	TEIFORM CDATA "AVAILABILITY"
>
<!ELEMENT SOURCEDESC (P | RECORDINGSTMT)+>
<!ATTLIST SOURCEDESC
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	DEFAULT (YES | NO) "NO"
	TEIFORM CDATA "SOURCEDESC"
>
<!ELEMENT RECORDINGSTMT (P+ | RECORDING+)>
<!ATTLIST RECORDINGSTMT
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "RECORDINGSTMT"
>
<!ELEMENT RECORDING (P+ | (RESPSTMT | EQUIPMENT | DATE)*)>
<!ATTLIST RECORDING
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	DEFAULT (YES | NO) "NO"
	TYPE (AUDIO | VIDEO) "AUDIO"
	DUR CDATA #IMPLIED
	TEIFORM CDATA "RECORDING"
>
<!ELEMENT EQUIPMENT (P)+>
<!ATTLIST EQUIPMENT
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	DEFAULT (YES | NO) "NO"
	TEIFORM CDATA "EQUIPMENT"
>
<!ELEMENT PROFILEDESC (CREATION?, LANGUSAGE*, PARTICDESC*, SETTINGDESC*)>
<!ATTLIST PROFILEDESC
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "PROFILEDESC"
>
<!ELEMENT CREATION (#PCDATA)>
<!ATTLIST CREATION
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "CREATION"
>
<!ELEMENT LANGUSAGE (P | LANGUAGE)+>
<!ATTLIST LANGUSAGE
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	DEFAULT (YES | NO) "NO"
	TEIFORM CDATA "LANGUSAGE"
>
<!ELEMENT LANGUAGE (#PCDATA)>
<!ATTLIST LANGUAGE
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	ID ID #IMPLIED
	WSD ENTITY #IMPLIED
	USAGE CDATA #IMPLIED
	TEIFORM CDATA "LANGUAGE"
>
<!ELEMENT PARTICDESC (P+ | ((PERSON | PERSONGRP)+, PARTICLINKS?))>
<!ATTLIST PARTICDESC
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	DEFAULT (YES | NO) "NO"
	TEIFORM CDATA "PARTICDESC"
>
<!ELEMENT PERSON ((AFFILIATION | BIRTH | EDUCATION | FIRSTLANG | LANGKNOWN | OCCUPATION | RESIDENCE | SOCECSTATUS)*)>
<!ATTLIST PERSON
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	ROLE CDATA #IMPLIED
	SEX (M | F | U) #IMPLIED
	AGE CDATA #IMPLIED
	RESTRICT (ALL | CITE | NONE) #IMPLIED
	TEIFORM CDATA "PERSON"
>
<!ELEMENT PERSONGRP (AFFILIATION | BIRTH | EDUCATION | FIRSTLANG | LANGKNOWN | OCCUPATION | RESIDENCE | SOCECSTATUS)*>
<!ATTLIST PERSONGRP
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	ROLE CDATA #IMPLIED
	SEX (M | F | U | X) #IMPLIED
	AGE CDATA #IMPLIED
	SIZE CDATA #IMPLIED
	TEIFORM CDATA "PERSONGRP"
>
<!ELEMENT BIRTH (#PCDATA)>
<!ATTLIST BIRTH
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	DATE CDATA #IMPLIED
	TEIFORM CDATA "BIRTH"
>
<!ELEMENT FIRSTLANG (#PCDATA)>
<!ATTLIST FIRSTLANG
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "FIRSTLANG"
>
<!ELEMENT LANGKNOWN (#PCDATA)>
<!ATTLIST LANGKNOWN
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "LANGKNOWN"
>
<!ELEMENT RESIDENCE (#PCDATA)>
<!ATTLIST RESIDENCE
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "RESIDENCE"
>
<!ELEMENT EDUCATION (#PCDATA)>
<!ATTLIST EDUCATION
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "EDUCATION"
>
<!ELEMENT AFFILIATION (#PCDATA)>
<!ATTLIST AFFILIATION
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "AFFILIATION"
>
<!ELEMENT OCCUPATION (#PCDATA)>
<!ATTLIST OCCUPATION
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	SCHEME IDREF #IMPLIED
	CODE IDREF #IMPLIED
	TEIFORM CDATA "OCCUPATION"
>
<!ELEMENT SOCECSTATUS (#PCDATA)>
<!ATTLIST SOCECSTATUS
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	SCHEME IDREF #IMPLIED
	CODE IDREF #IMPLIED
	TEIFORM CDATA "SOCECSTATUS"
>
<!ELEMENT PARTICLINKS (P+ | RELATION+)>
<!ATTLIST PARTICLINKS
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "PARTICLINKS"
>
<!ELEMENT RELATION EMPTY>
<!ATTLIST RELATION
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TYPE CDATA "PERSONAL"
	DESC CDATA #IMPLIED
	ACTIVE IDREFS #IMPLIED
	PASSIVE IDREFS #IMPLIED
	MUTUAL (Y | N) "Y"
	TEIFORM CDATA "RELATION"
>
<!ELEMENT SETTING (P+ | (NAME | TIME | LOCALE | ACTIVITY)*)>
<!ATTLIST SETTING
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	WHO IDREFS #IMPLIED
	TEIFORM CDATA "SETTING"
>
<!ELEMENT LOCALE (#PCDATA)>
<!ATTLIST LOCALE
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "LOCALE"
>
<!ELEMENT ACTIVITY (#PCDATA)>
<!ATTLIST ACTIVITY
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "ACTIVITY"
>
<!ELEMENT SETTINGDESC (P+ | SETTING+)>
<!ATTLIST SETTINGDESC
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	DEFAULT (YES | NO) "NO"
	TEIFORM CDATA "SETTINGDESC"
>
<!ELEMENT DATE (#PCDATA)>
<!ATTLIST DATE
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	CALENDAR CDATA #IMPLIED
	VALUE CDATA #IMPLIED
	CERTAINTY CDATA #IMPLIED
	TEIFORM CDATA "DATE"
>
<!ELEMENT TIME (#PCDATA)>
<!ATTLIST TIME
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	VALUE CDATA #IMPLIED
	TYPE (AM | PM | 24HOUR | DESCRIPTIVE) #IMPLIED
	ZONE CDATA #IMPLIED
	TEIFORM CDATA "TIME"
>
<!ELEMENT NAME (#PCDATA)>
<!ATTLIST NAME
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "NAME"
>
<!ELEMENT ADDRESS (#PCDATA)>
<!ATTLIST ADDRESS
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "ADDRESS"
>
<!ELEMENT ABBR (#PCDATA)>
<!ATTLIST ABBR
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	EXPAN CDATA #IMPLIED
	RESP IDREF #IMPLIED
	CERT CDATA #IMPLIED
	TYPE CDATA #IMPLIED
	TEIFORM CDATA "ABBR"
>
<!ELEMENT EXPAN (#PCDATA)>
<!ATTLIST EXPAN
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	ABBR CDATA #IMPLIED
	RESP IDREF #IMPLIED
	CERT CDATA #IMPLIED
	TYPE CDATA #IMPLIED
	TEIFORM CDATA "EXPAN"
>
<!ELEMENT SIC (#PCDATA)>
<!ATTLIST SIC
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	CORR CDATA #IMPLIED
	RESP IDREF #IMPLIED
	CERT CDATA #IMPLIED
	TEIFORM CDATA "SIC"
>
<!ELEMENT CORR (#PCDATA)>
<!ATTLIST CORR
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	SIC CDATA #IMPLIED
	RESP CDATA #IMPLIED
	CERT CDATA #IMPLIED
	TEIFORM CDATA "CORR"
>
<!ELEMENT UNCLEAR (#PCDATA)>
<!ATTLIST UNCLEAR
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	REASON CDATA #IMPLIED
	RESP CDATA #IMPLIED
	CERT CDATA #IMPLIED
	HAND IDREF #IMPLIED
	AGENT CDATA #IMPLIED
	TEIFORM CDATA "UNCLEAR"
>
<!ELEMENT SEG (#PCDATA)>
<!ATTLIST SEG
	ANA IDREFS #IMPLIED
	CORRESP IDREFS #IMPLIED
	NEXT IDREF #IMPLIED
	PREV IDREF #IMPLIED
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TYPE CDATA #IMPLIED
	FUNCTION CDATA #IMPLIED
	SUBTYPE CDATA #IMPLIED
	PART (Y | N | I | M | F) "N"
	TEIFORM CDATA "SEG"
>
<!ELEMENT FOREIGN (#PCDATA | SEG)*>
<!ATTLIST FOREIGN
	ID ID #IMPLIED
	N CDATA #IMPLIED
	REND CDATA #IMPLIED
	LANG IDREF #IMPLIED
	TEIFORM CDATA "FOREIGN"
>
<!ELEMENT OVERLAP (#PCDATA)>
<!ATTLIST OVERLAP
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "OVERLAP"
>
<!ELEMENT U (#PCDATA | ABBR | EXPAN | NAME | CORR | SIC | UNCLEAR | FOREIGN | HI | TITLE | OVERLAP | EVENT | PAUSE | SEG | SHIFT | U | WRITING | GAP)*>
<!ATTLIST U
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	START IDREF #IMPLIED
	END IDREF #IMPLIED
	DUR CDATA #IMPLIED
	TRANS (SMOOTH | LATCHING | OVERLAP | PAUSE) "SMOOTH"
	RESTRICT (ALL | CITE | NONE) #IMPLIED
	WHO IDREF #IMPLIED
	TEIFORM CDATA "U"
>
<!ELEMENT PAUSE EMPTY>
<!ATTLIST PAUSE
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	START IDREF #IMPLIED
	END IDREF #IMPLIED
	DUR CDATA #IMPLIED
	TYPE CDATA #IMPLIED
	WHO IDREF #IMPLIED
	TEIFORM CDATA "PAUSE"
>
<!ELEMENT GAP EMPTY>
<!ATTLIST GAP
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	DESC CDATA #IMPLIED
	REASON CDATA #IMPLIED
	RESP CDATA #IMPLIED
	AGENT CDATA #IMPLIED
	EXTENT IDREF #IMPLIED
	TEIFORM CDATA "GAP"
>
<!ELEMENT EVENT EMPTY>
<!ATTLIST EVENT
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	START IDREF #IMPLIED
	END IDREF #IMPLIED
	DUR CDATA #IMPLIED
	WHO IDREF #IMPLIED
	ITERATED (Y | N | U) "N"
	DESC CDATA #IMPLIED
	TEIFORM CDATA "EVENT"
>
<!ELEMENT WRITING (#PCDATA)>
<!ATTLIST WRITING
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	WHO IDREF #IMPLIED
	TYPE CDATA #IMPLIED
	SCRIPT IDREF #IMPLIED
	GRADUAL (Y | N | U) #IMPLIED
	TEIFORM CDATA "WRITING"
>
<!ELEMENT SHIFT EMPTY>
<!ATTLIST SHIFT
	ID ID #IMPLIED
	N CDATA #IMPLIED
	LANG IDREF #IMPLIED
	REND CDATA #IMPLIED
	WHO IDREF #IMPLIED
	FEATURE (TEMPO | LOUD | PITCH | TENSION | RHYTHM | VOICE) #REQUIRED
	NEW CDATA "NORMAL"
	TEIFORM CDATA "SHIFT"
>
<!ELEMENT P (#PCDATA | HI | TITLE | GAP)*>
<!ATTLIST P
	ID ID #IMPLIED
	N CDATA #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "P"
>
<!ELEMENT HI (#PCDATA)>
<!ATTLIST HI
	ID ID #IMPLIED
	N CDATA #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "HI"
>
<!ELEMENT TITLE (#PCDATA | HI)*>
<!ATTLIST TITLE
	ID ID #IMPLIED
	N CDATA #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "TITLE"
>
<!ELEMENT TEXT (BODY)>
<!ATTLIST TEXT
	ID ID #IMPLIED
	N CDATA #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "TEXT"
>
<!ELEMENT BODY (P | EVENT | PAUSE | SHIFT | U)+>
<!ATTLIST BODY
	ID ID #IMPLIED
	N CDATA #IMPLIED
	REND CDATA #IMPLIED
	TEIFORM CDATA "BODY"
>
<!--

<!ENTITY % ISOgrk1 PUBLIC
       "ISO 8879:1986//ENTITIES Greek Letters//EN">
%ISOgrk1;

<!ENTITY % ISOlat1 PUBLIC "ISO 8879-1986//ENTITIES Added Latin 1//EN">
%ISOlat1; 

<!ENTITY % ISOlat2 PUBLIC "ISO 8879-1986//ENTITIES Added Latin 2//EN">
%ISOlat2; 

<!ENTITY % ISOnum  
  PUBLIC   "ISO 8879-1986//ENTITIES Numeric and Special Graphic//EN">
%ISOnum;

<!ENTITY % ISOpub  PUBLIC "ISO 8879-1986//ENTITIES Publishing//EN">
%ISOpub; 

<!NOTATION cgm PUBLIC
  'ISO 8632:1987//NOTATION Computer Graphics Metafile//EN' >

<!NOTATION cgmchar PUBLIC
  'ISO 8632-2:1987//NOTATION CGM Character Encoding//EN' >

<!NOTATION jpeg PUBLIC
  'ISO DIS 10918//NOTATION JPEG Graphics Format//EN' >

<!NOTATION tiff PUBLIC
  '-//Aldus Corporation//NOTATION Tagged Image File Format//EN' >

<!NOTATION gif PUBLIC
  '-//Compuserve Information Service//NOTATION Graphics Interchange Format//EN' >

<!NOTATION sgml PUBLIC
  'ISO 8879:1986//NOTATION Standard Generalized Markup Language//EN' >

<!NOTATION wsd  PUBLIC
  '-//TEI P3-1994//NOTATION Writing System Declaration//EN' >
-->

=== CreativeCodingLab/corpusbrowser/corpora/MICASE-CD/Transcripts/lel320ju143.xml
<!DOCTYPE TEI.2 SYSTEM "micasex.dtd"> <TEI.2 ID="lel320ju143"> <TEIHEADER> <FILEDESC> <TITLESTMT> <TITLE> Renaissance to Modern Art History Lecture </TITLE> <TITLE> Rackham Div: HA </TITLE> </TITLESTMT> <PUBLICATIONSTMT> <PUBLISHER> Michigan Corpus of Academic Spoken English, English Language Institute, University of Michigan </PUBLISHER> <IDNO> LEL320JU143 </IDNO>  <AVAILABILITY> <P> The MICASE project is owned by the Regents of the University of Michigan, who hold the copyright.  The database has been developed by the English Language Institute, and the web interface by Digital Library Production Services.  The original DAT audiotapes are held in the English Language Institute and may be consulted by bona fide researchers under special arrangements.  The database is freely available at this website for study, teaching and research purposes, and copies of the transcripts may be distributed, as long as either this statement of availability or the citation given below appears in the text.  However, if any portion of this material is to be used for commercial purposes, such as for textbooks or tests, permission must be obtained in advance and a license fee may be required.  Furthermore, some restrictions apply on the citation of specific portions of some of the transcripts in educational presentations and publications; all such restrictions are noted at the end of this statement.  For further information about copyright permissions, please contact Dr. Sarah Briggs at slbriggs@umich.edu. </P>  <P> The recommended citation for MICASE is: R. C. Simpson, S. L. Briggs, J. Ovens, and J. M. Swales.  (1999) The Michigan Corpus of Academic Spoken English.  Ann Arbor, MI:  The Regents of the University of Michigan </P>  <P> RESTRICTIONS ON CITATION OF EXAMPLES:  NONE </P> </AVAILABILITY> </PUBLICATIONSTMT> <SOURCEDESC> <RECORDINGSTMT> <RECORDING DUR="50"> <DATE> March 21, 2001 </DATE> <EQUIPMENT> <P> TASCAM Digital Audio Tape Recorder with two external microphones </P> </EQUIPMENT> <RESPSTMT> <NAME> Jessica Rett </NAME> <RESP> Recording </RESP> <NAME> Darell Tibbles </NAME> <RESP> Transcribing </RESP> <NAME> Carrie Sue Kay Sulzer </NAME> <RESP> Rechecking </RESP> <NAME> Amy Burke </NAME> <RESP> Proofreading </RESP> <NAME> Rita Simpson </NAME> <RESP> Final Editing, 7/25/01 </RESP> </RESPSTMT> </RECORDING> </RECORDINGSTMT> </SOURCEDESC> </FILEDESC> <PROFILEDESC> <LANGUSAGE> <P> Primary Discourse Mode: MLG </P> <LANGUAGE ID="NS"> Native Speaker </LANGUAGE> </LANGUSAGE> <PARTICDESC> <PERSONGRP ROLE="Students" SIZE="150"> </PERSONGRP> <PERSONGRP ROLE="Speakers" SIZE="2"> </PERSONGRP> <PERSON ID="S1" LANG="NS" ROLE="SF, Instructor" SEX="F" RESTRICT="NONE" AGE="3"> </PERSON> <PERSON ID="S2" LANG="NS" ROLE="JU, Student" SEX="M" RESTRICT="NONE" AGE="1"> </PERSON> <PERSON ID="SS" LANG="NS" ROLE="JU, Student" SEX="U" RESTRICT="NONE" AGE="1"> </PERSON> <PERSON ID="SU-f" LANG="NS" ROLE="JU, Student" SEX="F" RESTRICT="NONE" AGE="1"> </PERSON> <PERSON ID="SU-m" LANG="NS" ROLE="JU, Student" SEX="M" RESTRICT="NONE" AGE="1"> </PERSON> </PARTICDESC> <SETTINGDESC> <SETTING> <P> Auditorium, Angell Hall </P> </SETTING> </SETTINGDESC> </PROFILEDESC> </TEIHEADER> <TEXT> <BODY> <U WHO="S1"> please remember that there's another field trip coming up this Sunday if you'd like to go you could sign up with Larry Henderson by the end of the week. also um, in the, coming events category Lorna Simpson is going to be speaking at the University Museum of Art tomorrow night. and she's a contemporary um, photography conceptual artist who's now moving into video, and is very articulate and interesting. so, since we've been spending all term on dead artists here's a chance to hear a living one. <EVENT WHO="SU-f" DESC="LAUGH"/> and her presentation i think is at seven thirty_ is there a question? </U> <U WHO="S2"> yeah where does the bus meet for the field trip? </U> <U WHO="S1"> oh the bus leaves from right outside the Museum of Art on State Street <OVERLAP> Sunday. </OVERLAP> <U WHO="S2"> <OVERLAP> okay </OVERLAP> </U> <PAUSE DUR=":06"/> okay we ended the class last time talking about Courbet's painting The Real Allegory. and we talked about that paradox how could you have a real, allegory. and we talked about Courbet, in the category of realism and this is an ism that, really was used by artists at the time (we've) discussed Courbet issuing a realist manifesto, um at the time, of his exhibition in eighteen fifty-five. now we discussed Courbet as v- being very self-conscious about what he was doing with art self-consciously a modern artist. um setting himself up, against the past in many ways. he's rejecting artistic institutions he's challenging artistic institutions by exhibiting outside the salon system. he's creating a persona around himself, of the artist as outsider the artist as revolutionary the artist as radical, the artist as somewhat bohemian but the artist also aligned with movements of liberation and with the working class. when he talks about real, it means on several levels at once. he talks about the need to draw his subject matter from real things that's the most obvious. you know he's not going to paint an angel if he hasn't seen one he's going to base his subject matter, on things in his own world that he could have seen. not ancient history, not literature, real means not ideal he's not going to romanticize mythologize glamorize um, real also means not imaginary. his art isn't going to be about fantasies, it's not going to appeal to the imagination it's supposed to be about the here and now. moreover for Courbet, real tends to be drawn from lower social classes. there's no reason why poor people are supposed to be more real, um than the artist's own friends, or, you could make you know supposedly people who buy art are real too. but at this time in the eighteen thirties and forties, um, he's working with an idea that contemporary middle-class and upper-class society is false, and that the real, the real people are the working people. so is there other ways, um that realism signifies_ realism means art without illusions. okay and now we're getting into some tricky territory, because the real allegory as we discussed, you know wasn't based on anything he could have seen exactly. an allegorical figure is supposed to be a figure that stands for an ideal. now we've seen how he deflates the idea of an allegory making the real allegory in this painting by taking the figure of a nude and saying no she doesn't stand for truth or beauty, if she's in this painting it must be because she's an artist's model and here you get a bunch of discarded clothing on the floor. usually when you have, you know nymph and shepherd and- shepherd in a landscape or, naked figure of truth you don't get truth's underwear, there in front of you. alright and so this is one way he makes an allegorical figure real and yet this is paradoxical because if she really is an artist's model which is one way that you would see a nude in a contemporary nineteenth century Parisian context. if she is an artist's model why isn't he painting her? um he's making a painting of a landscape here. so these are more ways he's bringing paradox into this work suggesting that it's not exactly a realist picture but nor is it an allegorical one. it's his version of a modern real allegory fit for the nineteenth century. <PAUSE DUR=":08"/> but there's another way that Courbet's art can be described as real also, and that has to do with his painting technique and that's why i've brought along the Burial at Ornans from eighteen forty-nine on the left and a close-up of it on the right. and you'll recall some of the comments that people made at the time about how Courbet applied his paint about his technique for painting. um he was criticized for not having any of the conventional technique. people thought he was inept people thought he was crude people thought he painted like a child, or that the paintings looked like folk woodcuts or that they looked unskilled. um they complained that they_ that the paintings didn't seem to use the conventional skills of perspective the perspective is all out of whack here. um and that the paint itself is kind of slopped onto the canvas with these heavy dark art- outlines, without the kind of careful brushwork or um gradual modulation of colors that was supported in academic technique. um what this painting does though Courbet might not have articulated it at the time, but what it does is to make no attempt to create an illusion in art. you don't_ you may be looking at real life but you don't have that sensation, that you're merely looking through a window, onto the real world. the paint gets in the way. you become very conscious that this is a piece of cloth with some kind of sticky substance smeared onto it and that somebody made it. um, centuries of technique had been developed to make the artist seem to disappear, that had been one of the, aspects of virtuosity Vermeer had aspired to that Van Eyck before him had dazzled people with these paintings where you couldn't see the brushwork where it was such a perfect likeness a perfect illusion. and in fact the skill of the artist then became in creating a perfect illusion. Courbet makes it impossible to maintain any sense of illusion when you're in front of one of his canvases, um because it's not about imitation of nature. instead the artist is inserting himself, and inserting the fact that art is a made thing. now this wouldn't be the first time that we find art that's self-conscious. modern artists didn't invent the idea that art is not a natural thing. um but Courbet, was doing it with his hands. and the idea that he introduces, in works like this um that the viewer is never allowed to forget that a canvas is a square you know that a painting is a canvas a canvas is a square piece of cloth stretched over, wood with paint put onto it. <EVENT DESC="LOUD BACKGROUND NOISE"/> at the end of that illusion, becomes an ide
